### PR TITLE
Update authorised_value to value in KohaRest.php

### LINKED ISSUE #2919: On Koha 23.11 authorised values are giving an error
image

Koha will map the api values and "authorised_value" is changing to be "value". Koha-Suomi is upgrading to newer version on May.

### PR DESCRIPTION
**Pull request by johannaraisa**
Fixes #2919.

### CODE REVIEW

**Comment by johannaraisa** [comment]
I added an issue but I guess I don't have right permissions to link it here.

**Review by EreMaijala — CHANGES_REQUESTED** [review]
If I understood properly, `authorised_value` will be changed to `value`, and `value` doesn't exist yet. If so, we need to check for both for back-compatibility, like:
```
// 'value' starting with Koha 23.11, 'authorised_value' for older versions:
$locations[$location['value'] ?? $location['authorised_value']] = $location;
```

**Comment by EreMaijala** [comment]
If you have Koha bug number that does the change, it would be nice to add it to the comment in my example for future reference.

**Comment by johannaraisa** [comment]
> If I understood properly, `authorised_value` will be changed to `value`, and `value` doesn't exist yet. If so, we need to check for both for back-compatibility, like:
> 
> ```
> // 'value' starting with Koha 23.11, 'authorised_value' for older versions:
> $locations[$location['value'] ?? $location['authorised_value']] = $location;
> ```

This would be even better solution! The bug number is, Bug 32981: Add endpoint to get AV for given category. Should I add a new pull request?

**Comment by EreMaijala** [comment]
@johannaraisa You can just push more commits to your branch and they'll be reflected here (though if you ever plan to post further PR's, I'd suggest creating a branch for each from dev first so that separate commits don't get mixed). I'll squash the result when merging, so it will result in a clean single commit in the dev branch. Thanks!

**Comment by johannaraisa** [comment]
Now the pull request is updated with a new commit. Yes, I should have done a new branch, will remember next time. :slightly_smiling_face:

**Comment by EreMaijala** [comment]
While working on this I noticed that this needed a bit of further work; see dc27fa135144b5252d3c774150ed11ecb574f3a8. Please let me know if I missed anything!

**Pull request merged**
