### PR TITLE
[ALLI-6134] Leave certain fileformats out of images section LIDO

### PR DESCRIPTION
**Pull request by LuomaJuha**
Checks the blacklist if the format is displayable.

### CODE REVIEW

**Comment by LuomaJuha** [comment]
Pieni muutos

**Comment by LuomaJuha** [comment]
Muutos tehty

**Comment by pasitii** [comment]
Add also GLB and OBJ to the "blacklist" (GLB file format is a binary form of glTF and OBJ is common format that represents 3D).

**Comment by LuomaJuha** [comment]
Siirretään lista configgiin, jotta saa lisäiltyä myöhemmin.

**Pull request closed without merging**
